services: 
  node-diw:
    image: node:22.12
    tty: true
    stdin_open: true
    working_dir: /appdiw
    volumes:
      - ./disseny_interficies:/appdiw
    ports:
      - "8082:5173"
  web:
    image: httpd
    tty: true
    stdin_open: true
    working_dir: /appdiw
    volumes:
      - ./disseny_interficies:/appdiw
    ports:
      - "84:80"
  qr:
    image: node:22
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./qr-app:/app
    environment:
      - PORT=3004
    ports:
      - "3009:3004"
  ngrok:
    image: ngrok/ngrok:latest
    stdin_open: true
    tty: true
    environment:
      - NGROK_AUTHTOKEN=358nrbVE5TZyJWdIQDzCw18iPDm_WtH2qjkMLQycPY5QNeJQ
    command:
      - http 80

# docker run --net=host -it -e NGROK_AUTHTOKEN=358nrbVE5TZyJWdIQDzCw18iPDm_WtH2qjkMLQycPY5QNeJQ ngrok/ngrok:latest http 80